### ISSUE TITLE
Anonymous inline struct types might not be fully supported yet

### ISSUE THREAD

**Issue by tsteckenborn** [mrbandler/cds2types#13]
There seem to be issues around [anonymous inline struct types](https://cap.cloud.sap/docs/cds/cdl#structured-types):

1. Without Associations:
`Unable to parse element '<arrayed type name>' on entity '<containing entity>'. It seems to be a CDS expression without a type definition, please add a type to it.`

2. With associations (in this case to Countries):
`Error: The target "sap.common.Countries" of the managed association "country" does not have keys`

Unfortunately not the time to dig into it at the moment. Maybe somebody else can take a shot at it.

Simple sample for 1.:

`entity Person {
  socialProfiles : {
    gitHub    : String;
    linkedIn  : String;
  };
}`

Simple sample for 2.:

```
using {Country, } from '@sap/cds/common';

entity Building {
  location  : {
    street  : String;
    city    : String;
    country : Country;
  };
}
```

**Comment by HeneryHawk** [comment]
Hi @tsteckenborn,

can you please provide a short example?

Regards
Simon

**Comment by tsteckenborn** [comment]
@HeneryHawk I should've checked in more detail. It's not about arrayed types, but anonymous inline struct types. Added a really minor sample cds above.

**Comment by HeneryHawk** [comment]
Hi @tsteckenborn,

I have released a version 2.7.0-beta.0 which should fix the problem. Can you please check this with this version?
This version should also fix the issue #14.

Regards
Simon

**Comment by HidirT** [comment]
Hello @HeneryHawk,

I'm currently facing the same issue. 
I tried the beta version, however the beta version seems to have solved the problem for anonymous inline structures for native types only.

This means, to stay with the examples from @tsteckenborn above, that Sample 1 is now fixed.
However, a typing for Sample 2 with Country still fails.

Version I use:
> Package         Current        Wanted  Latest  Location                Depended by
> cds2types  2.7.0-beta.0  2.7.0-beta.0   2.6.2  node_modules/cds2types  CDS2TYPES_test

The Error when run with --debug:

> Unable to write types. 
> Error: CDS compilation failed
> db\schema.cds:16:19-26: Error: The target "sap.common.Countries" of the managed association "country" does not have keys

Regards
Hidir

**Comment by HeneryHawk** [comment]
Hi @HidirT,

the error message regarding missing keys is **not** an error message coming from cds2types, but from the cds compiler itself.
This error message also comes directly when editing the entity in e.g. VSCode and **not** when compiling the cds definition to TypeScript.

![grafik](https://user-images.githubusercontent.com/35328833/142624564-cebe0ba9-58e9-43e8-a449-75b6b1aff98a.png)

Therefore please contact the colleagues at SAP.

Regards
Simon

**Comment by rafaelhoff** [comment]
In version 2.7.4, the issue is still there, given the example:

```
entity Books {
    key bookID {
            ID   : Integer;
            year : Integer;
        };
        title    : localized String(111);
        descr    : localized String(1111);
        author   : String(100);
        stock    : Integer;
        price    : Decimal(9, 2);
        currency : String(3);
}
```

would generate the following error: `Error: Unable to parse element 'bookID' on entity 'Books'. It seems to be a CDS expression without a type definition, please add a type to it.`

By debugging a bit, where the error occurs, all the child elements are visible. Could it be something that a type could be automatically created based on element name and attributes (`key` for example)?

**Comment by ffg91** [comment]
@HeneryHawk I have same issue as @rafaelhoff and @tsteckenborn , would it be possible to reopen?

Using version 3.0.0
